//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brady.ScrapRunner.Mobile.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brady.ScrapRunner.Mobile.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string AmountHint {
            get {
                return ResourceManager.GetString("AmountHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrive.
        /// </summary>
        public static string ArriveLabel {
            get {
                return ResourceManager.GetString("ArriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back On Duty.
        /// </summary>
        public static string BackOnDuty {
            get {
                return ResourceManager.GetString("BackOnDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Process.
        /// </summary>
        public static string CanProcess {
            get {
                return ResourceManager.GetString("CanProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Process.
        /// </summary>
        public static string CantProcess {
            get {
                return ResourceManager.GetString("CantProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity.
        /// </summary>
        public static string Commodity {
            get {
                return ResourceManager.GetString("Commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing this action will complete this trip.
        /// </summary>
        public static string CompleteTrip {
            get {
                return ResourceManager.GetString("CompleteTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing Trip Segment.
        /// </summary>
        public static string CompletingTripSegment {
            get {
                return ResourceManager.GetString("CompletingTripSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are arriving at:{0}{2}{1}{3}{1}{4}{0} Are you sure you want to mark trip as arrived?.
        /// </summary>
        public static string ConfirmArrivalMessage {
            get {
                return ResourceManager.GetString("ConfirmArrivalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving.
        /// </summary>
        public static string ConfirmArrivalTitle {
            get {
                return ResourceManager.GetString("ConfirmArrivalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you back on duty?.
        /// </summary>
        public static string ConfirmBackOnDuty {
            get {
                return ResourceManager.GetString("ConfirmBackOnDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to go en route to:{0}{2}{1}{3}{1}{4}{0}Are you sure you want to start this trip?.
        /// </summary>
        public static string ConfirmEnRouteMessage {
            get {
                return ResourceManager.GetString("ConfirmEnRouteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Enroute.
        /// </summary>
        public static string ConfirmEnrouteTitle {
            get {
                return ResourceManager.GetString("ConfirmEnrouteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmLabel {
            get {
                return ResourceManager.GetString("ConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to add the following terminal as a Return To Yard segment :{0}{2}{1}{3}{1}{4}{0}Are you sure you want to add this?.
        /// </summary>
        public static string ConfirmReturnToYardAdd {
            get {
                return ResourceManager.GetString("ConfirmReturnToYardAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to change the Return To Yard Segment from :{0}{2}{1}{3}{1}{4}{0}To:{0}{5}{1}{6}{1}{7}{0}Are you sure you want to change this?.
        /// </summary>
        public static string ConfirmReturnToYardEdit {
            get {
                return ResourceManager.GetString("ConfirmReturnToYardEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Complete.
        /// </summary>
        public static string ContainerComplete {
            get {
                return ResourceManager.GetString("ContainerComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container ID.
        /// </summary>
        public static string ContainerId {
            get {
                return ResourceManager.GetString("ContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Odometer.
        /// </summary>
        public static string CurrentOdometerHint {
            get {
                return ResourceManager.GetString("CurrentOdometerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Location.
        /// </summary>
        public static string CustomerLocation {
            get {
                return ResourceManager.GetString("CustomerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Directions.
        /// </summary>
        public static string DrivingDirectionsLabel {
            get {
                return ResourceManager.GetString("DrivingDirectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United States).
        /// </summary>
        public static string English_UnitedStates {
            get {
                return ResourceManager.GetString("English_UnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroute.
        /// </summary>
        public static string EnrouteButtonLabel {
            get {
                return ResourceManager.GetString("EnrouteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with Scale?.
        /// </summary>
        public static string FinishedScale {
            get {
                return ResourceManager.GetString("FinishedScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FinishLabel {
            get {
                return ResourceManager.GetString("FinishLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Trip.
        /// </summary>
        public static string FinishTripLabel {
            get {
                return ResourceManager.GetString("FinishTripLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced Logoff.
        /// </summary>
        public static string ForcedLogoff {
            get {
                return ResourceManager.GetString("ForcedLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are being logged off of the application by dispatch. 
        ///
        ///You will now be sent back to the login..
        /// </summary>
        public static string ForcedLogoffMessage {
            get {
                return ResourceManager.GetString("ForcedLogoffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Entry.
        /// </summary>
        public static string FuelEntry {
            get {
                return ResourceManager.GetString("FuelEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Capture.
        /// </summary>
        public static string GPSCapture {
            get {
                return ResourceManager.GetString("GPSCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add the current GPS coordinates as an arrival point for future usage?.
        /// </summary>
        public static string GPSCaptureMessage {
            get {
                return ResourceManager.GetString("GPSCaptureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        public static string GrossWeight {
            get {
                return ResourceManager.GetString("GrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left On Truck.
        /// </summary>
        public static string LeftOnTruck {
            get {
                return ResourceManager.GetString("LeftOnTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark containers as left on truck?.
        /// </summary>
        public static string LeftOnTruckContainerMessage {
            get {
                return ResourceManager.GetString("LeftOnTruckContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Miscellaneous Information.
        /// </summary>
        public static string LoadingMiscInformation {
            get {
                return ResourceManager.GetString("LoadingMiscInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Preferences.
        /// </summary>
        public static string LoadingPreferences {
            get {
                return ResourceManager.GetString("LoadingPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Trip Data.
        /// </summary>
        public static string LoadingTripData {
            get {
                return ResourceManager.GetString("LoadingTripData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Trip Information.
        /// </summary>
        public static string LoadingTripInformation {
            get {
                return ResourceManager.GetString("LoadingTripInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In.
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out of ScrapRunner?.
        /// </summary>
        public static string LogOutMessage {
            get {
                return ResourceManager.GetString("LogOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark this container as complete?.
        /// </summary>
        public static string MarkContainerComplete {
            get {
                return ResourceManager.GetString("MarkContainerComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Segment Successfully Created.
        /// </summary>
        public static string NewSegmentCreated {
            get {
                return ResourceManager.GetString("NewSegmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Stage.
        /// </summary>
        public static string NextStageLabel {
            get {
                return ResourceManager.GetString("NextStageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric value is required.
        /// </summary>
        public static string NumericRequired {
            get {
                return ResourceManager.GetString("NumericRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Odometer Reading.
        /// </summary>
        public static string Odometer {
            get {
                return ResourceManager.GetString("Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer must be between {0} and {1}..
        /// </summary>
        public static string OdometerOutOfRange {
            get {
                return ResourceManager.GetString("OdometerOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Reading.
        /// </summary>
        public static string OdometerReadingHint {
            get {
                return ResourceManager.GetString("OdometerReadingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A current odometer reading is required.
        /// </summary>
        public static string OdometerRequired {
            get {
                return ResourceManager.GetString("OdometerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordNotEmpty {
            get {
                return ResourceManager.GetString("PasswordNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be less than {0} characters..
        /// </summary>
        public static string PasswordOutOfRange {
            get {
                return ResourceManager.GetString("PasswordOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing this action will complete this trip. {0} Are you sure you want to do this?.
        /// </summary>
        public static string PerformActionLabel {
            get {
                return ResourceManager.GetString("PerformActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Full.
        /// </summary>
        public static string PickupFull {
            get {
                return ResourceManager.GetString("PickupFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Unit ID and Odometer Reading.
        /// </summary>
        public static string PowerUnitViewTitle {
            get {
                return ResourceManager.GetString("PowerUnitViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Scale Detail.
        /// </summary>
        public static string PublicScaleDetail {
            get {
                return ResourceManager.GetString("PublicScaleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Scale.
        /// </summary>
        public static string PublicScaleSummary {
            get {
                return ResourceManager.GetString("PublicScaleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Return To Yard.
        /// </summary>
        public static string ReturnToYardAdd {
            get {
                return ResourceManager.GetString("ReturnToYardAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Return To Yard.
        /// </summary>
        public static string ReturnToYardEdit {
            get {
                return ResourceManager.GetString("ReturnToYardEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Summary.
        /// </summary>
        public static string RouteSummary {
            get {
                return ResourceManager.GetString("RouteSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string SavingData {
            get {
                return ResourceManager.GetString("SavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Gross.
        /// </summary>
        public static string SecondGrossWeight {
            get {
                return ResourceManager.GetString("SecondGrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Segment Successfully Updated!.
        /// </summary>
        public static string SegmentUpdated {
            get {
                return ResourceManager.GetString("SegmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Exception Code.
        /// </summary>
        public static string SelectException {
            get {
                return ResourceManager.GetString("SelectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select A Yard.
        /// </summary>
        public static string SelectYard {
            get {
                return ResourceManager.GetString("SelectYard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Down.
        /// </summary>
        public static string SetDown {
            get {
                return ResourceManager.GetString("SetDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set this container down?.
        /// </summary>
        public static string SetDownContainerMessage {
            get {
                return ResourceManager.GetString("SetDownContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Receipt.
        /// </summary>
        public static string SignatureReceipt {
            get {
                return ResourceManager.GetString("SignatureReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in process failed..
        /// </summary>
        public static string SignInProcessFailed {
            get {
                return ResourceManager.GetString("SignInProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrapRunner Sign In.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare.
        /// </summary>
        public static string TareWeight {
            get {
                return ResourceManager.GetString("TareWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Detail.
        /// </summary>
        public static string TransactionDetail {
            get {
                return ResourceManager.GetString("TransactionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        public static string Trip {
            get {
                return ResourceManager.GetString("Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip(s) Canceled.
        /// </summary>
        public static string TripsCanceled {
            get {
                return ResourceManager.GetString("TripsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip(s) Marked Done.
        /// </summary>
        public static string TripsMarkedDone {
            get {
                return ResourceManager.GetString("TripsMarkedDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Trip(s).
        /// </summary>
        public static string TripsModified {
            get {
                return ResourceManager.GetString("TripsModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Trip(s).
        /// </summary>
        public static string TripsNew {
            get {
                return ResourceManager.GetString("TripsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip(s) Resequenced.
        /// </summary>
        public static string TripsResequenced {
            get {
                return ResourceManager.GetString("TripsResequenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch has changed the order of your trips..
        /// </summary>
        public static string TripsResequencedBody {
            get {
                return ResourceManager.GetString("TripsResequencedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip(s) Unassigned.
        /// </summary>
        public static string TripsUnassigned {
            get {
                return ResourceManager.GetString("TripsUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck ID.
        /// </summary>
        public static string TruckId {
            get {
                return ResourceManager.GetString("TruckId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck ID.
        /// </summary>
        public static string TruckIdHint {
            get {
                return ResourceManager.GetString("TruckIdHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified power unit id was found found.
        /// </summary>
        public static string TruckIdNotFound {
            get {
                return ResourceManager.GetString("TruckIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Id must be less than {0} characters..
        /// </summary>
        public static string TruckIdOutOfRange {
            get {
                return ResourceManager.GetString("TruckIdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid truck ID is required.
        /// </summary>
        public static string TruckIdRequired {
            get {
                return ResourceManager.GetString("TruckIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Process.
        /// </summary>
        public static string UnableToProcess {
            get {
                return ResourceManager.GetString("UnableToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string UserNameHint {
            get {
                return ResourceManager.GetString("UserNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string UserNameNotEmpty {
            get {
                return ResourceManager.GetString("UserNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be less than {0} characters..
        /// </summary>
        public static string UserNameOutOfRange {
            get {
                return ResourceManager.GetString("UserNameOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard/Scale Detail.
        /// </summary>
        public static string YardScaleDetail {
            get {
                return ResourceManager.GetString("YardScaleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard/Scale.
        /// </summary>
        public static string YardScaleLabel {
            get {
                return ResourceManager.GetString("YardScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard/Scale Summary.
        /// </summary>
        public static string YardScaleSummary {
            get {
                return ResourceManager.GetString("YardScaleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
