//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brady.ScrapRunner.Mobile.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brady.ScrapRunner.Mobile.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity.
        /// </summary>
        public static string Commodity {
            get {
                return ResourceManager.GetString("Commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are arriving at:{0}{2}{1}{3}{1}{4}{0} Are you sure you want to mark trip as arrived?.
        /// </summary>
        public static string ConfirmArrivalMessage {
            get {
                return ResourceManager.GetString("ConfirmArrivalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arriving.
        /// </summary>
        public static string ConfirmArrivalTitle {
            get {
                return ResourceManager.GetString("ConfirmArrivalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to go en route to:{0}{2}{1}{3}{1}{4}{0}Are you sure you want to start this trip?.
        /// </summary>
        public static string ConfirmEnRouteMessage {
            get {
                return ResourceManager.GetString("ConfirmEnRouteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Enroute.
        /// </summary>
        public static string ConfirmEnrouteTitle {
            get {
                return ResourceManager.GetString("ConfirmEnrouteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container ID.
        /// </summary>
        public static string ContainerId {
            get {
                return ResourceManager.GetString("ContainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Location.
        /// </summary>
        public static string CustomerLocation {
            get {
                return ResourceManager.GetString("CustomerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (United States).
        /// </summary>
        public static string English_UnitedStates {
            get {
                return ResourceManager.GetString("English_UnitedStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left On Truck.
        /// </summary>
        public static string LeftOnTruck {
            get {
                return ResourceManager.GetString("LeftOnTruck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark containers as left on truck?.
        /// </summary>
        public static string LeftOnTruckContainerMessage {
            get {
                return ResourceManager.GetString("LeftOnTruckContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In.
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numeric value is required.
        /// </summary>
        public static string NumericRequired {
            get {
                return ResourceManager.GetString("NumericRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Odometer Reading.
        /// </summary>
        public static string Odometer {
            get {
                return ResourceManager.GetString("Odometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer must be between {0} and {1}..
        /// </summary>
        public static string OdometerOutOfRange {
            get {
                return ResourceManager.GetString("OdometerOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A current odometer reading is required.
        /// </summary>
        public static string OdometerRequired {
            get {
                return ResourceManager.GetString("OdometerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordNotEmpty {
            get {
                return ResourceManager.GetString("PasswordNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be less than {0} characters..
        /// </summary>
        public static string PasswordOutOfRange {
            get {
                return ResourceManager.GetString("PasswordOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup Full.
        /// </summary>
        public static string PickupFull {
            get {
                return ResourceManager.GetString("PickupFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Unit ID and Odometer Reading.
        /// </summary>
        public static string PowerUnitViewTitle {
            get {
                return ResourceManager.GetString("PowerUnitViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Summary.
        /// </summary>
        public static string RouteSummary {
            get {
                return ResourceManager.GetString("RouteSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Down.
        /// </summary>
        public static string SetDown {
            get {
                return ResourceManager.GetString("SetDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to set this container down?.
        /// </summary>
        public static string SetDownContainerMessage {
            get {
                return ResourceManager.GetString("SetDownContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Receipt.
        /// </summary>
        public static string SignatureReceipt {
            get {
                return ResourceManager.GetString("SignatureReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in process failed..
        /// </summary>
        public static string SignInProcessFailed {
            get {
                return ResourceManager.GetString("SignInProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        public static string Trip {
            get {
                return ResourceManager.GetString("Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck ID.
        /// </summary>
        public static string TruckId {
            get {
                return ResourceManager.GetString("TruckId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified power unit id was found found.
        /// </summary>
        public static string TruckIdNotFound {
            get {
                return ResourceManager.GetString("TruckIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Id must be less than {0} characters..
        /// </summary>
        public static string TruckIdOutOfRange {
            get {
                return ResourceManager.GetString("TruckIdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid truck ID is required.
        /// </summary>
        public static string TruckIdRequired {
            get {
                return ResourceManager.GetString("TruckIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        public static string UserNameHint {
            get {
                return ResourceManager.GetString("UserNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string UserNameNotEmpty {
            get {
                return ResourceManager.GetString("UserNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be less than {0} characters..
        /// </summary>
        public static string UserNameOutOfRange {
            get {
                return ResourceManager.GetString("UserNameOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard/Scale Detail.
        /// </summary>
        public static string YardScaleDetail {
            get {
                return ResourceManager.GetString("YardScaleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard/Scale Summary.
        /// </summary>
        public static string YardScaleSummary {
            get {
                return ResourceManager.GetString("YardScaleSummary", resourceCulture);
            }
        }
    }
}
