#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Brady.ScrapRunner.Mobile.Droid.Resource", IsApplication=true)]

namespace Brady.ScrapRunner.Mobile.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Brady.ScrapRunner.Mobile.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Brady.ScrapRunner.Mobile.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Brady.ScrapRunner.Mobile.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Brady.ScrapRunner.Mobile.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Brady.ScrapRunner.Mobile.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Brady.ScrapRunner.Mobile.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Brady.ScrapRunner.Mobile.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Brady.ScrapRunner.Mobile.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Brady.ScrapRunner.Mobile.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Brady.ScrapRunner.Mobile.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Brady.ScrapRunner.Mobile.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Brady.ScrapRunner.Mobile.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Brady.ScrapRunner.Mobile.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Brady.ScrapRunner.Mobile.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Attribute.MvxBind = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Attribute.MvxItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Attribute.MvxLang = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Attribute.MvxSource = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Attribute.MvxTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Id.MvvmCrossTagId = global::Brady.ScrapRunner.Mobile.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Id.MvxBindingTagUnique = global::Brady.ScrapRunner.Mobile.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.ApplicationName = global::Brady.ScrapRunner.Mobile.Droid.Resource.String.ApplicationName;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.String.Hello = global::Brady.ScrapRunner.Mobile.Droid.Resource.String.Hello;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxBinding = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxControl = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxExpandableListView = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxImageView = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxListView = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Plugins.Sqlite.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Brady.ScrapRunner.Mobile.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::Splat.Resource.String.library_name = global::Brady.ScrapRunner.Mobile.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Brady.ScrapRunner.Mobile.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Brady.ScrapRunner.Mobile.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarColor = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int ahBarLength = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int ahBarWidth = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public const int ahCircleColor = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int ahDelayMillis = 2130771982;
			
			// aapt resource value: 0x7f010010
			public const int ahRadius = 2130771984;
			
			// aapt resource value: 0x7f01000b
			public const int ahRimColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int ahRimWidth = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int ahSpinSpeed = 2130771981;
			
			// aapt resource value: 0x7f010007
			public const int ahText = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int ahTextColor = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int ahTextSize = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int accent = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int material_blue_500 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int material_blue_700 = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int material_gray_700 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int material_gray_900 = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawericon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawericon2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_alarm_on_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_alarm_on_white_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_assignment_late_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_assignment_turned_in_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_directions_white_36dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_errorstatus = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_keyboard_arrow_right_black_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_local_shipping_white_36dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_loupe_white_36dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_place_white_36dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_settings_white_36dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_settings_white_48dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_successstatus = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int loginsplash800x1280 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int loginsplash800x1280_2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int roundedbg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int roundedbgdark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int scraprunnertemplogo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int splash = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int loadingImage = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int loadingProgressBar = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int loadingProgressWheel = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int textViewStatus = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FirstView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loading = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingimage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingprogress = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SplashScreen = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int ScrapRunnerTheme = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int ScrapRunnerTheme_ActionBar_TitleTextStyle = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int ScrapRunnerTheme_ActionBarStyle = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int ScrapRunnerTheme_Base = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] ProgressWheel = new int[] {
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
