using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SQLite.Net.Attributes;

namespace Brady.ScrapRunner.Mobile.Models
{
    [Table("DriverStatus")]
    public class DriverStatusModel
    {
        [PrimaryKey, MaxLength(10)]
        public string EmployeeId { get; set; }
        [MaxLength(10)]
        public string TripNumber { get; set; }
        [MaxLength(2)]
        public string TripSegNumber { get; set; }
        [MaxLength(4)]
        public string TripSegType { get; set; }
        [MaxLength(1)]
        public string TripAssignStatus { get; set; }
        [MaxLength(1)]
        public string TripStatus { get; set; }
        [MaxLength(1)]
        public string TripSegStatus { get; set; }
        /// <summary>
        /// Known as DriverStatus in the scraprunner database.
        /// </summary>
        [MaxLength(1)]
        public string Status { get; set; }
        [MaxLength(10)]
        public string TerminalId { get; set; }
        [MaxLength(10)]
        public string RegionId { get; set; }
        [MaxLength(16)]
        public string PowerId { get; set; }
        [MaxLength(1)]
        public string DriverArea { get; set; }
        [MaxLength(12)]
        public string MDTId { get; set; }
        public DateTime? LoginDateTime { get; set; }
        public DateTime? ActionDateTime { get; set; }
        public int? DriverCumMinutes { get; set; }
        public int? Odometer { get; set; }
        [MaxLength(1)]
        public string RFIDFlag { get; set; }
        [MaxLength(6)]
        public string RouteTo { get; set; }
        public DateTime? LoginProcessedDateTime { get; set; }
        [MaxLength(1)]
        public string GPSAutoGeneratedFlag { get; set; }
        public DateTime? ContainerMasterDateTime { get; set; }
        [MaxLength(5)]
        public string DelayCode { get; set; }
        [MaxLength(1)]
        public string PrevDriverStatus { get; set; }
        [MaxLength(6)]
        public string MdtVersion { get; set; }
        [MaxLength(10)]
        public string GPSXmitFlag { get; set; }
        public int? SendHHLogoffFlag { get; set; }
        public DateTime? TerminalMasterDateTime { get; set; }
        public int? DriverLCID { get; set; }
    }
}
