using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Brady.ScrapRunner.Domain.Models;
using BWF.DataServices.Metadata.Fluent.Abstract;

namespace Brady.ScrapRunner.Domain.Metadata
{
    public class DriverHistoryMetadata : TypeMetadataProvider<DriverHistory>
    {
        public DriverHistoryMetadata()
        {

            AutoUpdatesByDefault();
            
            StringProperty(x => x.Id)
                .IsHiddenInEditor()
                .IsNotEditableInGrid();

            StringProperty(x => x.EmployeeId)
                .IsId()
                .DisplayName("Employee Id");

            StringProperty(x => x.TripNumber)
                .IsId()
                .DisplayName("Trip Number");

            IntegerProperty(x => x.DriverSeqNumber)
                .IsId()
                .DisplayName("Driver Seq Number");

            StringProperty(x => x.TripSegNumber);
            StringProperty(x => x.TripSegType);
            StringProperty(x => x.TripSegTypeDesc);
            StringProperty(x => x.TripAssignStatus);
            StringProperty(x => x.TripAssignStatusDesc);
            StringProperty(x => x.TripStatus);
            StringProperty(x => x.TripStatusDesc);
            StringProperty(x => x.TripSegStatus);
            StringProperty(x => x.TripSegStatusDesc);
            StringProperty(x => x.DriverStatus);
            StringProperty(x => x.DriverStatusDesc);
            StringProperty(x => x.DriverName);
            StringProperty(x => x.TerminalId);
            StringProperty(x => x.TerminalName);
            StringProperty(x => x.RegionId);
            StringProperty(x => x.RegionName);
            StringProperty(x => x.PowerId);
            StringProperty(x => x.DriverArea);
            StringProperty(x => x.MDTId);
            DateProperty(x => x.LoginDateTime);
            DateProperty(x => x.ActionDateTime);
            IntegerProperty(x => x.DriverCumMinutes);
            IntegerProperty(x => x.Odometer);
            StringProperty(x => x.DestCustType);
            StringProperty(x => x.DestCustTypeDesc);
            StringProperty(x => x.DestCustHostCode);
            StringProperty(x => x.DestCustName);
            StringProperty(x => x.DestCustAddress1);
            StringProperty(x => x.DestCustAddress2);
            StringProperty(x => x.DestCustCity);
            StringProperty(x => x.DestCustState);
            StringProperty(x => x.DestCustZip);
            StringProperty(x => x.DestCustCountry);
            StringProperty(x => x.GPSAutoGeneratedFlag);
            StringProperty(x => x.GPSXmitFlag);
            StringProperty(x => x.MdtVersion);

            ViewDefaults()
                .Property(x => x.EmployeeId)
                .Property(x => x.TripNumber)
                .Property(x => x.DriverSeqNumber)
                .Property(x => x.TripSegNumber)
                .Property(x => x.TripSegType)
                .Property(x => x.TripSegTypeDesc)
                .Property(x => x.TripAssignStatus)
                .Property(x => x.TripAssignStatusDesc)
                .Property(x => x.TripStatus)
                .Property(x => x.TripStatusDesc)
                .Property(x => x.TripSegStatus)
                .Property(x => x.TripSegStatusDesc)
                .Property(x => x.DriverStatus)
                .Property(x => x.DriverStatusDesc)
                .Property(x => x.DriverName)
                .Property(x => x.TerminalId)
                .Property(x => x.TerminalName)
                .Property(x => x.RegionId)
                .Property(x => x.RegionName)
                .Property(x => x.PowerId)
                .Property(x => x.DriverArea)
                .Property(x => x.MDTId)
                .Property(x => x.LoginDateTime)
                .Property(x => x.ActionDateTime)
                .Property(x => x.DriverCumMinutes)
                .Property(x => x.Odometer)
                .Property(x => x.DestCustType)
                .Property(x => x.DestCustTypeDesc)
                .Property(x => x.DestCustHostCode)
                .Property(x => x.DestCustName)
                .Property(x => x.DestCustAddress1)
                .Property(x => x.DestCustAddress2)
                .Property(x => x.DestCustCity)
                .Property(x => x.DestCustState)
                .Property(x => x.DestCustZip)
                .Property(x => x.DestCustCountry)
                .Property(x => x.GPSAutoGeneratedFlag)
                .Property(x => x.GPSXmitFlag)
                .Property(x => x.MdtVersion)

                .OrderBy(x => x.EmployeeId)
                .OrderBy(x => x.TripNumber)
                .OrderBy(x => x.DriverSeqNumber);
        }
    }
}
